# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4878fa81b49dac7a6778f3350974ced0"
name = "App_From_bulilder_2026"
application_url = "https://formbuilder.it3.in"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[app_proxy]
url = "https://formbuilder.it3.in/proxy"
prefix = "apps"
subpath = "form-builder"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [ ]
